### ISSUE TITLE
Can't find driver for WisCore RAK4631 board

### ISSUE THREAD

**Issue by JuriShalkin** [RAKWireless/RAK-nRF52-Arduino#5]
Can't find driver for WisCore RAK4631 board
I have reinstalled support for the nrf52 platform for Arduino IDE several times, but still there is no way to download the sketch, since the drivers for the board are not installed.
System - Win7 64, Arduino IDE 1.8.1.

**Comment by beegee-tokyo** [comment]
Is the board detected when you connect it to your computer?
Is Windows asking you to install drivers?
Did you install the CP2104 drivers manually, as mentioned [here](https://github.com/RAKWireless/RAK-nRF52-Arduino#drivers)

**Comment by JuriShalkin** [comment]
When the board is connected, 2 new devices appear in the system: a composite USB device and a WisCore RAK4631 board. Drivers for a composite usb device are installed, but for WisCore RAK4631 boards are not.
I have previously installed drivers for CP210x for other devices. Now, when I try to update the drivers, I get a message from the installation wizard that there are no devices that need to be updated.

**Comment by beegee-tokyo** [comment]
I checked on my computer. I didn't install any additional drivers.

An empty RAK4631 (as newly delivered) or after double reset it shows as Disk drive and as USB Serial Device:
![image](https://user-images.githubusercontent.com/512690/118274729-114bc700-b4f8-11eb-9888-96e52c7b7998.png)

When a sketch is flashed, the RAK4631 is shown as USB Serial Device:
![image](https://user-images.githubusercontent.com/512690/118274414-ae5a3000-b4f7-11eb-9f9c-2fa48ea9f656.png)

There was no need to install any additional driver.

In Arduino IDE, do you see a COM port like this:
![image](https://user-images.githubusercontent.com/512690/118274938-58d25300-b4f8-11eb-87f4-62a49013e4e5.png)

Did you try different USB cables and different USB ports?

**Comment by JuriShalkin** [comment]
This is the first time I hear about a double reset, but I did it, after that a new device appeared in the system.
![feather_nrf52840](https://user-images.githubusercontent.com/38093036/118354259-b65fb180-b583-11eb-8c26-0256a694455c.png)
But the serial port driver is still not found. 
![driver_after_double_reboot](https://user-images.githubusercontent.com/38093036/118354266-bfe91980-b583-11eb-9de1-6d2604f0f0c1.png)
You are talking about RAK4631, but it says RAK463 on my board, does it matter?
I used the bundled cable and not only and different ports, the result is the same.

**Comment by beegee-tokyo** [comment]
RAK4630 (printed on the label) is a stamp module used on the WisBlock Core RAK4631. Doesn't matter.

I have no solution for you. I will have to search for someone with a Windows 7 PC. I have only Windows 10 for testing.

Maybe you can post your problem on the [RAK forum for WisBlock](https://forum.rakwireless.com/c/wisblock/67) More people can help there.

**Comment by JuriShalkin** [comment]
I solved the problem! It was necessary to install the drivers from adafruit.
https://github.com/adafruit/Adafruit_Windows_Drivers/releases/tag/2.5.0.0
I think it is necessary to add information about this to the manual.

**Comment by beegee-tokyo** [comment]
Thank you for sharing yous solution.
I guess I never saw the problem because I had other BSP's installed before and the drivers made have already been installed.

I added the link to the [README.md](https://github.com/RAKWireless/RAK-nRF52-Arduino#usb-driver)
