### ISSUE TITLE
Examples are not up to date

### ISSUE THREAD

**Issue by battosai30** [RAKWireless/RAK-nRF52-Arduino#8]
Hi,

I don't know if other files are concerned, but this one for example : /RAK4631/Communications/LoRa/LoRaWAN/RAK4631-DeepSleep-LoRaWan
is not the same as here : https://github.com/RAKWireless/WisBlock/tree/master/examples/RAK4630/communications/LoRa/LoRaWAN/RAK4631-DeepSleep-LoRaWan

**Comment by beegee-tokyo** [comment]
Yes, the examples that are integrated in the BSP are older than the examples in the WisBlock repo.

To update the examples in the BSP, we would have to release a new BSP version every time, which is not an easy thing to do.

It is always better to use the examples from the WisBlock repo.
